# File added by Ash
name: Cypress Tests # A name for the workflow: whatever you want

on: [push] # A trigger ("when I push code, trigger the jobs in this workflow")

jobs: # A series of jobs. Pay attention to indentation - super important in yml files
  cypress-run: # Give the job a name: whatever you want
    runs-on: ubuntu-latest # tell the job what image to run on
    steps:
      - name: Checkout # A name for step one
        uses: actions/checkout@v2 # use the standard checkout action?
      - name: Cypress run  # A name for the second step
        # leverage the Cypress maintained GitHub Action which has all the stuff bundled already for you:
        # such as installing depedencies, running the project, and running the tests for you
        uses: cypress-io/github-action@v2
        with:
          build: npm run build #in turn runs  "npm run lint" just as designated in package.json file 
          start: npm start #in turn runs "node ./scripts/start.js" just as designated in package.json file
          record: false
        




